"""empty message

Revision ID: 18563b4e537f
Revises: 2334c0935f2d
Create Date: 2015-04-23 20:17:09.118883

"""

# revision identifiers, used by Alembic.
revision = '18563b4e537f'
down_revision = '2334c0935f2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('is_private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'is_private')
    ### end Alembic commands ###
