"""empty message

Revision ID: 1dc91f4f50ae
Revises: 267fb00f7a5d
Create Date: 2015-03-17 22:13:42.538996

"""

# revision identifiers, used by Alembic.
revision = '1dc91f4f50ae'
down_revision = '267fb00f7a5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
