"""empty message

Revision ID: 2334c0935f2d
Revises: 1dc91f4f50ae
Create Date: 2015-03-17 22:25:30.737302

"""

# revision identifiers, used by Alembic.
revision = '2334c0935f2d'
down_revision = '1dc91f4f50ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
