"""empty message

Revision ID: 267fb00f7a5d
Revises: 4cc007786a5f
Create Date: 2015-03-17 13:47:29.324597

"""

# revision identifiers, used by Alembic.
revision = '267fb00f7a5d'
down_revision = '4cc007786a5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatusersdetail', sa.Column('special_key', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatusersdetail', 'special_key')
    ### end Alembic commands ###
