"""empty message

Revision ID: 2f05aa094418
Revises: 34e31b509d7d
Create Date: 2015-04-23 21:35:08.265010

"""

# revision identifiers, used by Alembic.
revision = '2f05aa094418'
down_revision = '34e31b509d7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('chat', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'longitude')
    op.drop_column('chat', 'latitude')
    ### end Alembic commands ###
