"""empty message

Revision ID: 3402700b05f8
Revises: 540720ed53c1
Create Date: 2015-04-23 22:09:43.534105

"""

# revision identifiers, used by Alembic.
revision = '3402700b05f8'
down_revision = '540720ed53c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
