"""empty message

Revision ID: 34e31b509d7d
Revises: 18563b4e537f
Create Date: 2015-04-23 20:19:54.537698

"""

# revision identifiers, used by Alembic.
revision = '34e31b509d7d'
down_revision = '18563b4e537f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
