"""empty message

Revision ID: 37e576bb07fd
Revises: 4e0a644a156b
Create Date: 2015-04-23 22:57:59.474933

"""

# revision identifiers, used by Alembic.
revision = '37e576bb07fd'
down_revision = '4e0a644a156b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
