"""empty message

Revision ID: 4cc007786a5f
Revises: 8ab564f4724
Create Date: 2015-03-16 18:15:18.754780

"""

# revision identifiers, used by Alembic.
revision = '4cc007786a5f'
down_revision = '8ab564f4724'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
