"""empty message

Revision ID: 4e0a644a156b
Revises: 3402700b05f8
Create Date: 2015-04-23 22:57:50.971894

"""

# revision identifiers, used by Alembic.
revision = '4e0a644a156b'
down_revision = '3402700b05f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
