"""empty message

Revision ID: 540720ed53c1
Revises: 2f05aa094418
Create Date: 2015-04-23 21:37:45.436331

"""

# revision identifiers, used by Alembic.
revision = '540720ed53c1'
down_revision = '2f05aa094418'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
