"""empty message

Revision ID: 8ab564f4724
Revises: 3dbf80099b1
Create Date: 2015-03-16 18:11:02.378699

"""

# revision identifiers, used by Alembic.
revision = '8ab564f4724'
down_revision = '3dbf80099b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
